# config.yaml


# Samplelist file
input_list: "/path/to/file/samples.txt"


# Directories
base_dir: "/path/to/project/dir/"
input_dir: "subdirectory/to/raw/input/"
output_dir: "subdir/to/pipeline_out/for/project/"
databases_dir: "/path/to/databases/"


# RQCFilter2 parameters:
rqcfilter2:
  database: "RQCFilterData/"
  memory: 40
  threads: 4


# Kraken2 parameters
kraken2:
  database: "path/to/kraken2/database"
  threads: 40


# Bracken parameters
bracken:
  database: "path/to/bracken/database"
  level: "S" # Taxonomic level of interest
  read_length: 150
  threshold: 10


# RGI parameters
rgi:
  cardDB: "path/to/card/database"
  aligner: "kma"
  threads: 40


# ResFinder parameters:
resfinder:
  db_res: "path/to/databases/resfinder/resfinder_db"


# ResFinderFG parameters:
resfinderfg:
  db_res: "path/to/databases/resfinder/resfinderfg_db"
  threads: 8


# MetaSPADES parameters
metaspades:
  threads: 80
  memory: 490000 # In MB
  time: 60 * 24
